# Generated by Django 5.1 on 2024-09-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_userdata_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactdata',
        ),
    ]
