# Generated by Django 5.1 on 2024-09-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_contactdata_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
    ]
