# Generated by Django 5.1.7 on 2025-04-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_contactdata_emaill_contactdata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
