# Generated by Django 5.1.7 on 2025-04-08 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_contactdata_image_userdata_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.userdata'),
        ),
    ]
